trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm audit
  displayName: 'Install dependencies and audit'

- script: |
    npm start
  displayName: 'Start Application'